ping:
    type: presenter
    methods: [get]
    path: ping
    middleware: ["auth:user"]
    presenter: ping

user:
    type: group
    children: _user.yaml

auth:
    type: group
    children: _auth.yaml

user_chatroom:
    type: group
    children: _user_chatroom.yaml