ping:
    type: presenter
    methods: [get]
    path: ping
    presenter: ping

user:
    type: group
    children: _user.yaml

auth:
    type: group
    children: _auth.yaml

chatroom:
    type: group
    children: _chatroom.yaml

user_chatroom:
    type: group
    children: _user_chatroom.yaml